### ISSUE TITLE
[Design] Login and Register page

### ISSUE THREAD

**Issue by cup-noodlehS** [maxellmilay/beacon-final#32]
> Get Figma design approval first before starting development 🖖 

> tyt lang di mani urget hwehwe

- https://www.figma.com/file/1jkzOYiAYVEmQqRRGF6tJP/beacon?type=design&node-id=0-1&mode=design&t=XHjckDSqGPPCm2vY-0

**Comment by Loweso** [comment]
Whatchu think @cup-noodlehS 

![image](https://github.com/maxellmilay/beacon-final/assets/119489421/dca5327f-544e-4cc4-bff2-1e7c8d55a223)
![image](https://github.com/maxellmilay/beacon-final/assets/119489421/aba5b64e-979e-40c2-b86c-1106114e0c35)

**Comment by cup-noodlehS** [comment]
@Loweso NOICEEE WAN ALL GUDS 🔥🔥

pwede naka start code ana 🌈 

cc. @maxellmilay

**Comment by cup-noodlehS** [comment]
@Loweso chat lang if need ka help with git
